import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, Check, X } from 'lucide-react';
import { SERVICES_DATA, getService } from '@/data/servicesData';
import { PROJECTS_DATA } from '@/data/projectsData';
import { ProjectCard } from '@/components/portfolio/ProjectCard';
import { SITE_URL } from '@/data/studioConfig';

export function generateStaticParams() { return SERVICES_DATA.map(({ id }) => ({ slug: id })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const service = getService(params.slug); if (!service) return {};
  return { title: service.title, description: service.shortDescription, alternates: { canonical: `/services/${service.id}` }, openGraph: { title: `${service.title} in India`, description: service.shortDescription, url: `${SITE_URL}/services/${service.id}` } };
}

export default function ServiceDetailPage({ params }: { params: { slug: string } }) {
  const service = getService(params.slug); if (!service) notFound();
  const related = PROJECTS_DATA.filter((project) => service.id === 'architecture' ? project.categories.includes('Architecture') : project.categories.includes(service.id === 'interior-design' ? 'Interior' : 'Exterior'));
  const schema = { '@context': 'https://schema.org', '@type': 'Service', name: service.title, description: service.shortDescription, areaServed: { '@type': 'Country', name: 'India' }, provider: { '@type': 'ProfessionalService', name: 'AURA Architecture Studio', url: SITE_URL } };
  const breadcrumbs = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL }, { '@type': 'ListItem', position: 2, name: 'Services', item: `${SITE_URL}/services` }, { '@type': 'ListItem', position: 3, name: service.title, item: `${SITE_URL}/services/${service.id}` }] };
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: service.faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) };
  return <><nav aria-label="Breadcrumb" className="page-shell py-4 text-sm text-[var(--muted)]"><Link href="/">Home</Link> / <Link href="/services">Services</Link> / <span aria-current="page">{service.title}</span></nav><header className="border-y bg-[var(--surface)]"><div className="page-shell grid lg:grid-cols-2"><div className="flex flex-col justify-center py-14 pr-0 lg:pr-12"><p className="eyebrow">{service.eyebrow}</p><h1 className="display-title mt-5">{service.title}</h1><p className="body-copy mt-6">{service.shortDescription}</p><p className="mt-6 text-sm leading-7"><b>Who it is for:</b> {service.whoFor}</p><Link href={`/contact?service=${service.id}`} className="focus-ring mt-8 flex min-h-12 w-fit items-center gap-2 bg-[var(--clay)] px-6 font-bold text-white">Book a consultation <ArrowRight size={18} /></Link></div><div className="relative min-h-[380px] lg:min-h-[600px]"><Image src={service.image.src} alt={service.image.alt} fill priority sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /><span className="absolute bottom-3 left-3 bg-[var(--charcoal)] px-3 py-2 text-xs text-white">Concept visualisation</span></div></div></header>
  <section className="section-space"><div className="page-shell grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Problems this solves</p><h2 className="section-title mt-4">Turn uncertainty into a coordinated brief.</h2><ul className="mt-7 space-y-3">{service.problems.map((item) => <li key={item} className="flex gap-3"><Check className="text-[var(--clay)]" size={19} />{item}</li>)}</ul></div><div className="surface-card p-6 sm:p-8"><h2 className="font-display text-3xl">Scope can include</h2><ul className="mt-6 grid gap-3 sm:grid-cols-2">{service.scope.map((item) => <li key={item} className="flex gap-2 text-sm"><Check className="mt-0.5 shrink-0 text-[var(--clay)]" size={17} />{item}</li>)}</ul></div></div></section>
  <section className="section-space bg-[var(--charcoal)] text-[#f4f0e8]"><div className="page-shell"><p className="eyebrow !text-[#e4b481]">What you receive</p><h2 className="section-title mt-4">Deliverables matched to the appointment.</h2><div className="mt-8 grid gap-px bg-stone-600 sm:grid-cols-2 lg:grid-cols-3">{service.deliverables.map((item, i) => <div key={item} className="bg-[var(--charcoal)] p-6"><span className="text-xs text-[#e4b481]">{String(i + 1).padStart(2, '0')}</span><h3 className="mt-3 font-display text-xl">{item}</h3></div>)}</div></div></section>
  <section className="section-space"><div className="page-shell"><p className="eyebrow">Typical process</p><h2 className="section-title mt-4">A sequence with decision points.</h2><ol className="mt-8 grid gap-4 md:grid-cols-3">{service.process.map((item, i) => <li key={item} className="surface-card p-5"><span className="text-xs font-bold text-[var(--clay)]">STEP {i + 1}</span><h3 className="mt-2 font-display text-xl">{item}</h3></li>)}</ol><p className="body-copy mt-8 max-w-3xl"><b className="text-[var(--ink)]">Timeline guidance:</b> {service.timeline}</p></div></section>
  <section className="section-space border-y bg-[var(--surface)]"><div className="page-shell grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Clear boundaries</p><h2 className="section-title mt-4">Possible exclusions</h2></div><ul className="space-y-4">{service.exclusions.map((item) => <li key={item} className="flex gap-3 text-sm leading-6"><X className="mt-0.5 shrink-0 text-[var(--clay)]" size={18} />{item}</li>)}</ul></div></section>
  {related.length > 0 && <section className="section-space"><div className="page-shell"><p className="eyebrow">Related concept studies</p><h2 className="section-title mt-4">See the scope in context.</h2><div className="mt-8 grid gap-6 md:grid-cols-2">{related.slice(0, 2).map((project) => <ProjectCard key={project.id} project={project} />)}</div></div></section>}
  <section className="section-space bg-[var(--surface)]"><div className="page-shell grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><h2 className="section-title">Frequently asked</h2><div className="divide-y border-y">{service.faqs.map((faq) => <details key={faq.question} className="py-5"><summary className="cursor-pointer font-bold">{faq.question}</summary><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{faq.answer}</p></details>)}</div></div></section>
  <section className="bg-[var(--clay)] py-14 text-white"><div className="page-shell flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-display text-4xl">Is this the right scope for your project?</h2><Link href={`/contact?service=${service.id}`} className="focus-ring flex min-h-12 items-center justify-center bg-white px-6 font-bold text-[var(--clay)]">Book a consultation</Link></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, '\\u003c') }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs).replace(/</g, '\\u003c') }} /></>;
}
