import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check } from 'lucide-react';
import { STUDIO_CONFIG } from '@/data/studioConfig';

export const metadata: Metadata = { title: 'About the Studio', description: 'A clear, climate-aware approach to architecture, interior design, and exterior design in India.', alternates: { canonical: '/about' } };

export default function AboutPage() {
  return <>
    <header className="section-space border-b bg-[var(--surface)]"><div className="page-shell"><p className="eyebrow">About the studio</p><h1 className="display-title mt-5 max-w-4xl">Design decisions grounded in place, use, and buildability.</h1><p className="body-copy mt-6 max-w-3xl">AURA brings architecture, interior design, and exterior design into one coordinated conversation. The goal is not a signature style; it is a property that works coherently from the plot edge to the room detail.</p></div></header>
    <section className="section-space"><div className="page-shell grid gap-10 lg:grid-cols-2"><div className="relative min-h-[480px]"><Image src="/images/founders.png" alt="Placeholder studio portrait awaiting authentic team photography" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /><span className="absolute bottom-3 left-3 bg-[var(--charcoal)] px-3 py-2 text-xs text-white">Placeholder image — replace with authentic team photography</span></div><div className="flex flex-col justify-center"><p className="eyebrow">What clients can expect</p><h2 className="section-title mt-4">One brief. Visible stages. Fewer disconnected decisions.</h2><p className="body-copy mt-5">The studio’s public credentials, leadership biographies, office address, project statistics, and memberships have been intentionally withheld until they can be verified. This protects prospective clients from relying on demo content.</p><ul className="mt-7 space-y-3">{['A scope written around deliverables', 'Climate and maintenance considered early', 'Interior and exterior coordination', 'Options explained with trade-offs', 'Site involvement defined before appointment'].map((item) => <li key={item} className="flex gap-3"><Check className="mt-0.5 shrink-0 text-[var(--clay)]" size={18} />{item}</li>)}</ul><Link href="/contact" className="focus-ring mt-8 inline-flex min-h-12 w-fit items-center gap-2 bg-[var(--clay)] px-6 font-bold text-white">Discuss your project <ArrowRight size={18} /></Link></div></div></section>
    <section className="section-space bg-[var(--charcoal)] text-[#f4f0e8]"><div className="page-shell grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[['Context', 'Plot, neighbourhood, climate, regulations, and local construction realities.'], ['Function', 'Daily routines, circulation, storage, privacy, and adaptability.'], ['Material', 'Availability, craft, weathering, upkeep, and honest junctions.'], ['Coordination', 'Drawings, consultants, vendors, decisions, and site communication.']].map(([title, text]) => <article key={title} className="border-l border-stone-600 p-5"><h2 className="font-display text-2xl">{title}</h2><p className="mt-3 text-sm leading-6 text-stone-300">{text}</p></article>)}</div></section>
    {!STUDIO_CONFIG.serviceArea.verified && <section className="border-b bg-[var(--surface)] py-8"><div className="page-shell"><p className="text-sm"><b>Client update required:</b> add the verified studio city, service radius, legal entity, registration details, and team information in the studio configuration before publishing those facts.</p></div></section>}
  </>;
}
