import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Design Process', description: 'A transparent architecture, interior, and exterior design process from consultation to handover.', alternates: { canonical: '/process' } };
const stages = [
  ['01', 'Consultation', 'Goals, location, property type, decision-makers, broad budget, desired start, and the right service scope.', 'Written next steps and information checklist'],
  ['02', 'Site study & brief', 'Survey information, orientation, climate, access, regulations, existing conditions, routines, storage, and priorities.', 'Confirmed brief, constraints, and scope'],
  ['03', 'Concept design', 'Plans, zoning, massing, facade or room direction, key material ideas, and clear alternatives.', 'Concept package for approval'],
  ['04', '3D visualisation', 'Important spatial, interior, and exterior decisions are made visible before detailed documentation.', 'Selected views and material direction'],
  ['05', 'Technical drawings', 'Drawings are developed for the agreed scope and coordinated with appointed consultants.', 'Issue-based drawing package'],
  ['06', 'Material selection', 'Finishes, fixtures, colours, lighting, joinery, facade materials, and maintenance implications.', 'Schedules and approved samples'],
  ['07', 'Site coordination', 'Clarifications, review cadence, vendor interfaces, deviations, and recorded decisions.', 'Site notes and design responses'],
  ['08', 'Handover', 'Final review, open-item tracking, documentation collation, and care or maintenance guidance where applicable.', 'Handover checklist'],
];
export default function ProcessPage() { return <><header className="section-space border-b bg-[var(--surface)]"><div className="page-shell"><p className="eyebrow">Process</p><h1 className="display-title mt-5 max-w-4xl">Know what is being decided—and what comes next.</h1><p className="body-copy mt-6 max-w-3xl">The exact stages change by service and appointment. The principle does not: each stage has inputs, decisions, deliverables, and a recorded approval before the project advances.</p></div></header><section className="section-space"><div className="page-shell"><ol className="space-y-4">{stages.map(([number, title, detail, output]) => <li key={number} className="surface-card grid gap-4 p-6 sm:grid-cols-[80px_1fr_.6fr] sm:items-start"><span className="font-display text-4xl text-[var(--sand)]">{number}</span><div><h2 className="font-display text-2xl">{title}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{detail}</p></div><div className="border-l pl-4 text-sm"><b className="block text-xs uppercase tracking-wider text-[var(--clay)]">Typical output</b><span className="mt-2 block">{output}</span></div></li>)}</ol></div></section><section className="bg-[var(--charcoal)] py-14 text-white"><div className="page-shell flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-display text-4xl">Start with a clear project brief.</h2><Link href="/contact" className="focus-ring flex min-h-12 items-center justify-center bg-[var(--clay)] px-6 font-bold">Book a consultation</Link></div></section></>; }
