import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, MessageCircle } from 'lucide-react';
import { SERVICES_DATA } from '@/data/servicesData';
import { PROJECTS_DATA } from '@/data/projectsData';
import { STUDIO_CONFIG, whatsappUrl } from '@/data/studioConfig';
import { ProjectCard } from '@/components/portfolio/ProjectCard';

const process = ['Consultation', 'Site study & brief', 'Concept design', '3D visualisation', 'Technical drawings', 'Material selection', 'Execution coordination', 'Handover'];
const approach = [
  ['Climate before style', 'Orientation, shade, cross-ventilation, glare, and rainfall are studied for the project’s actual regional climate.'],
  ['Materials that age well', 'Kota stone, laterite, terracotta, Indian marble, lime plaster, screens, and exterior finishes are selected only where suitable.'],
  ['One coordinated property', 'Architecture, interiors, and exteriors share one spatial, material, lighting, and services direction.'],
  ['Choices made visible', 'Clear stages, documented decisions, and 3D views reduce assumptions before work reaches site.'],
];
const faqs = [
  ['Where does the studio work?', STUDIO_CONFIG.serviceArea.verified ? STUDIO_CONFIG.serviceArea.display : 'The studio works in India. The home city, travel radius, and site-visit availability must be confirmed during the first call.'],
  ['Do you design both interiors and exteriors?', 'Yes. Architecture, full-home interiors, and exterior elevation or facade design can be commissioned separately or coordinated as one complete-property scope.'],
  ['How are design fees calculated?', 'Fees depend on scope, area, project stage, location, deliverables, and site involvement. A project-specific fee is confirmed in a written proposal after the initial consultation.'],
  ['Can you work remotely?', 'Remote consultation is available for suitable design stages. Surveys, approvals, execution, and site reviews may require verified local support.'],
  ['Do you offer turnkey execution?', 'Turnkey interior or construction execution is not presented as a standard service until the studio confirms availability for the project location.'],
  ['Can you accommodate Vastu?', 'Yes, as an optional client preference balanced with climate, function, structure, access, and local regulations.'],
];

export default function HomePage() {
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) };
  return <>
    <section className="relative min-h-[calc(100svh-72px)] overflow-hidden bg-[var(--charcoal)] text-[#f8f4ec]">
      <Image src="/images/indian_hero.png" alt="Concept visualisation of a contemporary Indian house with deep shade and terracotta screens" fill priority sizes="100vw" className="object-cover object-center opacity-55" />
      <div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/55 to-black/10" />
      <div className="page-shell relative flex min-h-[calc(100svh-72px)] items-end pb-32 pt-12 sm:items-center sm:py-20">
        <div className="max-w-4xl"><p className="eyebrow !text-[#e4b481]">Architecture studio in India</p><h1 className="display-title mt-5 max-w-4xl">Architecture, interiors, and exteriors—designed as one property.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-stone-200 sm:text-xl sm:leading-8">Clear planning, material-aware interiors, and climate-responsive facades for new homes and thoughtful renovations.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="focus-ring flex min-h-12 items-center justify-center gap-2 bg-[var(--clay)] px-6 font-bold text-white">Book a design consultation <ArrowRight size={18} /></Link><Link href="/portfolio" className="focus-ring flex min-h-12 items-center justify-center border border-white/50 px-6 font-bold">Explore our projects</Link><a href={whatsappUrl('Hello AURA, I would like to book a design consultation.')} className="focus-ring flex min-h-12 items-center justify-center gap-2 border border-white/50 px-5 font-bold sm:hidden"><MessageCircle size={18} /> WhatsApp</a></div><p className="mt-5 text-xs text-stone-300">Hero image: concept visualisation, not completed client work.</p></div>
      </div>
    </section>
    <section aria-label="Studio facts" className="border-b bg-[var(--surface)]"><div className="page-shell grid grid-cols-2 divide-x py-6 sm:grid-cols-4"><div className="px-3 first:pl-0"><b className="block text-sm">Service area</b><span className="text-xs text-[var(--muted)]">India · exact radius on enquiry</span></div><div className="px-3"><b className="block text-sm">Project types</b><span className="text-xs text-[var(--muted)]">New homes & renovations</span></div><div className="mt-5 border-t px-3 pt-5 sm:mt-0 sm:border-t-0 sm:pt-0"><b className="block text-sm">Consultations</b><span className="text-xs text-[var(--muted)]">Remote & site-based</span></div><div className="mt-5 border-t px-3 pt-5 sm:mt-0 sm:border-t-0 sm:pt-0"><b className="block text-sm">Credentials</b><span className="text-xs text-[var(--muted)]">Verification pending</span></div></div></section>
    <section className="section-space"><div className="page-shell"><p className="eyebrow">Three connected capabilities</p><h2 className="section-title mt-4 max-w-3xl">Start with one room, one facade, or the whole property.</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{SERVICES_DATA.map((service, index) => <article key={service.id} className="surface-card p-6 sm:p-8"><span className="font-display text-5xl text-[var(--sand)]">0{index + 1}</span><p className="eyebrow mt-6">{service.eyebrow}</p><h3 className="mt-2 font-display text-3xl">{service.title}</h3><p className="mt-4 leading-7 text-[var(--muted)]">{service.shortDescription}</p><Link href={`/services/${service.id}`} className="focus-ring mt-6 inline-flex min-h-11 items-center gap-2 font-bold text-[var(--clay)]">Explore {service.title.toLowerCase()} <ArrowRight size={17} /></Link></article>)}</div></div></section>
    <section className="section-space border-y bg-[var(--surface)]"><div className="page-shell"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Selected studies</p><h2 className="section-title mt-4">Work shown honestly.</h2><p className="body-copy mt-4 max-w-2xl">Until verified project photography and details are provided, the portfolio is clearly labelled as concept visualisation—not completed client work.</p></div><Link href="/portfolio" className="focus-ring flex min-h-11 items-center gap-2 font-bold">View portfolio <ArrowRight size={17} /></Link></div><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{PROJECTS_DATA.filter((project) => project.featured).map((project, index) => <ProjectCard key={project.id} project={project} priority={index === 0} />)}</div></div></section>
    <section className="section-space"><div className="page-shell grid gap-8 lg:grid-cols-2"><div className="relative min-h-[420px] overflow-hidden"><Image src="/images/indian_courtyard.png" alt="Concept visualisation of a material-led interior with a planted courtyard" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /><span className="absolute bottom-3 left-3 bg-[var(--charcoal)] px-3 py-2 text-xs text-white">Interior concept visualisation</span></div><div className="flex flex-col justify-center"><p className="eyebrow">Inside and outside, together</p><h2 className="section-title mt-4">The front elevation should belong to the rooms behind it.</h2><p className="body-copy mt-5">Window proportions affect furniture planning. Balconies affect shade. Exterior lighting affects the entrance sequence. Treating interior and exterior design together produces fewer compromises and a calmer material story.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Room planning aligned with openings', 'Facade materials carried into thresholds', 'Lighting coordinated across edges', 'Weathering and maintenance considered early'].map((item) => <p key={item} className="flex gap-2 text-sm"><Check className="mt-0.5 shrink-0 text-[var(--clay)]" size={17} />{item}</p>)}</div><div className="mt-7 flex gap-5"><Link href="/services/interior-design" className="font-bold text-[var(--clay)]">Interior design →</Link><Link href="/services/exterior-design" className="font-bold text-[var(--clay)]">Exterior design →</Link></div></div></div></section>
    <section className="section-space bg-[var(--moss)] text-white"><div className="page-shell"><p className="eyebrow !text-[#f1d0a5]">Indian design approach</p><h2 className="section-title mt-4 max-w-3xl">Regional climate changes the answer.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-white/80">Coastal, warm-humid, hot-dry, composite, and temperate locations need different responses. The design starts with the site—not a fixed visual formula.</p><div className="mt-10 grid gap-px bg-white/20 sm:grid-cols-2 lg:grid-cols-4">{approach.map(([title, text]) => <div key={title} className="bg-[var(--moss)] p-6"><h3 className="font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-white/75">{text}</p></div>)}</div></div></section>
    <section className="section-space"><div className="page-shell"><p className="eyebrow">A visible process</p><h2 className="section-title mt-4">From first conversation to handover.</h2><ol className="mt-10 grid gap-0 border-l sm:grid-cols-2 sm:border-l-0 lg:grid-cols-4">{process.map((step, index) => <li key={step} className="border-b p-5 sm:border-l"><span className="text-xs font-bold text-[var(--clay)]">{String(index + 1).padStart(2, '0')}</span><h3 className="mt-3 font-display text-xl">{step}</h3></li>)}</ol></div></section>
    <section className="section-space"><div className="page-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Common questions</p><h2 className="section-title mt-4">Useful answers before the first call.</h2></div><div className="divide-y border-y">{faqs.map(([q, a]) => <details key={q} className="group py-5"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-4 font-bold">{q}<span aria-hidden="true" className="text-2xl text-[var(--clay)]">+</span></summary><p className="max-w-3xl pb-2 pr-10 text-sm leading-7 text-[var(--muted)]">{a}</p></details>)}</div></div></section>
    <section className="bg-[var(--clay)] py-14 text-white"><div className="page-shell flex flex-col gap-7 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/75">Have a site or a space in mind?</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Tell us what needs to work better.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="focus-ring flex min-h-12 items-center justify-center bg-white px-6 font-bold text-[var(--clay)]">Book a design consultation</Link><a href={`tel:${STUDIO_CONFIG.contact.phone.replace(/\s/g, '')}`} className="focus-ring flex min-h-12 items-center justify-center border border-white px-6 font-bold">{STUDIO_CONFIG.contact.phone}</a></div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, '\\u003c') }} />
  </>;
}
