import type { Metadata } from 'next';
import Link from 'next/link';
import { STUDIO_CONFIG } from '@/data/studioConfig';

export const metadata: Metadata = { title: 'Website Terms', description: 'Terms for using the AURA Architecture Studio website and indicative cost estimator.', alternates: { canonical: '/terms' } };

export default function TermsPage() {
  return <div className="page-shell section-space max-w-4xl"><p className="eyebrow">Website terms</p><h1 className="display-title mt-4">Terms of use</h1><p className="mt-4 text-sm text-[var(--muted)]">Last updated: 16 September 2026</p><div className="mt-10 space-y-8 text-sm leading-7 text-[var(--muted)]"><section><h2 className="font-display text-2xl text-[var(--ink)]">Website content</h2><p className="mt-2">This site explains possible design services. Availability, deliverables, timelines, consultants, fees, travel, execution support, and site visits are confirmed only in a written proposal. Concept images and placeholders are labelled and must not be treated as completed client work.</p></section><section><h2 className="font-display text-2xl text-[var(--ink)]">Estimator</h2><p className="mt-2">Estimator outputs use demonstration defaults for early planning. They are not quotations, professional fee proposals, tenders, construction budgets, or statements of current market rates. Taxes, approvals, consultant fees, site conditions, procurement, and execution can materially change cost.</p></section><section><h2 className="font-display text-2xl text-[var(--ink)]">Intellectual property</h2><p className="mt-2">Content may not be reproduced for commercial use without permission. Third-party rights, if any, remain with their respective owners. Authentic ownership details should be added when final client assets are supplied.</p></section><section><h2 className="font-display text-2xl text-[var(--ink)]">Contact</h2><p className="mt-2">Questions can be sent to <a href={`mailto:${STUDIO_CONFIG.contact.email}`} className="text-[var(--clay)] underline">{STUDIO_CONFIG.contact.email}</a>. Governing-law and legal-entity clauses should be added after the client confirms the registered business details and jurisdiction.</p></section></div><Link href="/" className="focus-ring mt-10 inline-flex min-h-11 items-center font-bold text-[var(--clay)]">← Return home</Link></div>;
}
