'use client';

import React from 'react';
import Link from 'next/link';
import { Scale, ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-8 text-neutral-800 dark:text-neutral-200">
      <Link href="/" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-amber-500 hover:underline">
        <ArrowLeft className="w-4 h-4" />
        Return to Home
      </Link>

      <div className="space-y-3 border-b border-neutral-200 dark:border-neutral-800 pb-6">
        <span className="text-xs uppercase tracking-widest text-amber-500 font-bold flex items-center gap-2">
          <Scale className="w-4 h-4" />
          Legal Terms
        </span>
        <h1 className="font-serif text-4xl font-bold text-neutral-900 dark:text-neutral-100">
          Terms of Service
        </h1>
        <p className="text-xs text-neutral-500">Last Updated: January 1, 2026</p>
      </div>

      <div className="space-y-6 text-sm leading-relaxed text-neutral-600 dark:text-neutral-400">
        <section className="space-y-2">
          <h2 className="font-serif text-xl font-bold text-neutral-900 dark:text-neutral-100">1. Intellectual Property & Copyright</h2>
          <p>
            All architectural drawings, 3D renders, project photographs, logos, and monograph copy published on this web application are the exclusive intellectual property of AURA Architecture & Urban Studio LLC protected under US and international copyright law.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-serif text-xl font-bold text-neutral-900 dark:text-neutral-100">2. Estimator Disclaimer</h2>
          <p>
            Estimates generated by our online Cost & Scope Estimator tool are indicative and provided solely for initial client self-qualification. Formal binding fee proposals require a signed AIA Professional Services Agreement following a site feasibility study.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="font-serif text-xl font-bold text-neutral-900 dark:text-neutral-100">3. Governing Law</h2>
          <p>
            These terms are governed by the laws of the State of California without regard to conflict of law principles.
          </p>
        </section>
      </div>
    </div>
  );
}
