import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check } from 'lucide-react';
import { SERVICES_DATA } from '@/data/servicesData';

export const metadata: Metadata = { title: 'Architecture, Interior & Exterior Design Services', description: 'Residential architecture, home interior design, and exterior elevation or facade design for new properties and renovations in India.', alternates: { canonical: '/services' } };

export default function ServicesPage() {
  return <><header className="section-space border-b bg-[var(--surface)]"><div className="page-shell"><p className="eyebrow">Services</p><h1 className="display-title mt-5 max-w-5xl">Three disciplines. One coordinated property.</h1><p className="body-copy mt-6 max-w-3xl">Choose a focused engagement or combine architecture, interiors, and exteriors. Every proposal identifies deliverables, exclusions, timeline assumptions, and site involvement.</p></div></header><div>{SERVICES_DATA.map((service, index) => <section key={service.id} className={`section-space ${index % 2 ? 'bg-[var(--surface)]' : ''}`}><div className="page-shell grid gap-9 lg:grid-cols-2 lg:items-center"><div className={`relative min-h-[380px] ${index % 2 ? 'lg:order-2' : ''}`}><Image src={service.image.src} alt={service.image.alt} fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover" /><span className="absolute bottom-3 left-3 bg-[var(--charcoal)] px-3 py-2 text-xs text-white">Concept visualisation</span></div><div><p className="eyebrow">0{index + 1} · {service.eyebrow}</p><h2 className="section-title mt-4">{service.title}</h2><p className="body-copy mt-5">{service.shortDescription}</p><p className="mt-5 text-sm leading-7"><b>Best suited to:</b> {service.whoFor}</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{service.scope.slice(0, 8).map((item) => <li key={item} className="flex gap-2 text-sm"><Check className="mt-0.5 shrink-0 text-[var(--clay)]" size={17} />{item}</li>)}</ul><Link href={`/services/${service.id}`} className="focus-ring mt-7 inline-flex min-h-12 items-center gap-2 bg-[var(--charcoal)] px-6 font-bold text-[#f4f0e8]">Scope, process & FAQ <ArrowRight size={18} /></Link></div></div></section>)}</div></>;
}
