import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, Check } from 'lucide-react';
import { PROJECTS_DATA } from '@/data/projectsData';
import { formatArea } from '@/lib/format';
import { BeforeAfterSlider } from '@/components/interactive/BeforeAfterSlider';
import { SITE_URL } from '@/data/studioConfig';

export function generateStaticParams() { return PROJECTS_DATA.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const project = PROJECTS_DATA.find((item) => item.slug === params.slug); if (!project) return {};
  return { title: project.seo.title, description: project.seo.description, alternates: { canonical: `/portfolio/${project.slug}` }, openGraph: { title: project.seo.title, description: project.seo.description, images: [{ url: project.coverImage.src, alt: project.coverImage.alt }] } };
}

export default function ProjectDetailPage({ params }: { params: { slug: string } }) {
  const project = PROJECTS_DATA.find((item) => item.slug === params.slug); if (!project) notFound();
  const breadcrumbs = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL }, { '@type': 'ListItem', position: 2, name: 'Portfolio', item: `${SITE_URL}/portfolio` }, { '@type': 'ListItem', position: 3, name: project.title, item: `${SITE_URL}/portfolio/${project.slug}` }] };
  return <><nav aria-label="Breadcrumb" className="page-shell py-4 text-sm text-[var(--muted)]"><Link href="/">Home</Link> / <Link href="/portfolio">Portfolio</Link> / <span aria-current="page">{project.title}</span></nav><header className="relative min-h-[68vh] bg-[var(--charcoal)] text-white"><Image src={project.coverImage.src} alt={project.coverImage.alt} fill priority sizes="100vw" className="object-cover opacity-55" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/35 to-transparent" /><div className="page-shell relative flex min-h-[68vh] flex-col justify-end py-12"><Link href="/portfolio" className="focus-ring mb-7 flex min-h-11 w-fit items-center gap-2 text-sm font-bold"><ArrowLeft size={17} /> Portfolio</Link><p className="eyebrow !text-[#e4b481]">{project.categories.join(' · ')} · {project.status}</p><h1 className="display-title mt-4 max-w-4xl">{project.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-stone-200">{project.summary}</p><p className="mt-4 text-xs text-stone-300">Image classification: concept visualisation. Location and client details are not claimed.</p></div></header>
  <section className="border-b bg-[var(--surface)]"><dl className="page-shell grid grid-cols-2 gap-0 py-6 sm:grid-cols-4"><div className="border-r p-3"><dt className="text-xs uppercase text-[var(--muted)]">Status</dt><dd className="mt-1 font-bold capitalize">{project.status}</dd></div><div className="border-r p-3"><dt className="text-xs uppercase text-[var(--muted)]">Property</dt><dd className="mt-1 font-bold">{project.propertyType}</dd></div><div className="border-r p-3"><dt className="text-xs uppercase text-[var(--muted)]">Area</dt><dd className="mt-1 font-bold">{formatArea(project.builtUpAreaSqFt)}</dd></div><div className="p-3"><dt className="text-xs uppercase text-[var(--muted)]">Location</dt><dd className="mt-1 font-bold">{project.locationVerified ? `${project.city}, ${project.state}` : 'Not published / unverified'}</dd></div></dl></section>
  <section className="section-space"><div className="page-shell grid gap-10 lg:grid-cols-[1.3fr_.7fr]"><div><p className="eyebrow">The brief</p><h2 className="section-title mt-4">What this study explores.</h2><p className="body-copy mt-5">{project.brief}</p><div className="mt-9 grid gap-5 sm:grid-cols-2"><article className="surface-card p-6"><h3 className="font-display text-2xl">Challenge</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{project.challenge}</p></article><article className="surface-card p-6"><h3 className="font-display text-2xl">Design response</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{project.solution}</p></article></div></div><aside className="surface-card p-6"><h2 className="font-display text-2xl">Scope of work</h2><ul className="mt-5 space-y-3">{project.scope.map((item) => <li key={item} className="flex gap-2 text-sm"><Check className="shrink-0 text-[var(--clay)]" size={17} />{item}</li>)}</ul><h3 className="mt-8 text-xs font-bold uppercase tracking-wider text-[var(--clay)]">Material direction</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{project.materials.join(' · ')}</p><h3 className="mt-7 text-xs font-bold uppercase tracking-wider text-[var(--clay)]">Design style</h3><p className="mt-2 text-sm">{project.designStyle}</p></aside></div></section>
  {project.beforeAfter && <section className="section-space bg-[var(--surface)]"><div className="page-shell"><p className="eyebrow">Comparison study</p><h2 className="section-title mb-8 mt-4">Existing condition and concept direction.</h2><BeforeAfterSlider data={project.beforeAfter} /></div></section>}
  <section className="section-space"><div className="page-shell"><p className="eyebrow">Visual study</p><h2 className="section-title mt-4">Concept gallery.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2">{project.galleryImages.map((image) => <figure key={image.src + image.alt}><div className="relative aspect-[4/3] overflow-hidden"><Image src={image.src} alt={image.alt} fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover" /></div><figcaption className="mt-2 text-xs text-[var(--muted)]">{image.classification.replaceAll('-', ' ')}</figcaption></figure>)}</div></div></section>
  <section className="bg-[var(--clay)] py-14 text-white"><div className="page-shell flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-display text-4xl">Planning a similar scope?</h2><Link href={`/contact?service=${project.categories.includes('Interior') ? 'interior-design' : project.categories.includes('Exterior') ? 'exterior-design' : 'architecture'}&project=${project.slug}`} className="focus-ring flex min-h-12 items-center justify-center bg-white px-6 font-bold text-[var(--clay)]">Discuss your project</Link></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs).replace(/</g, '\\u003c') }} /></>;
}
